spring:
  datasource:
    username: ${DB_USERNAME:jira}
    password: ${DB_PASSWORD:JiraRush}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:3d0d8738e65881fff266}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID:329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          gitlab:
            client-id: ${GITLAB_CLIENT_ID:b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494}
            client-secret: ${GITLAB_CLIENT_SECRET}
  mail:
    username: ${MAIL_USERNAME:jira4jr@gmail.com}
    password: ${MAIL_PASSWORD}

